### PR TITLE
Updated net-ssh gem for ssh key type ed25519

### PR DESCRIPTION
**Pull request by Korkey128k**

### CODE REVIEW

**Comment by mapyo** [comment]
@pioneerskies 
Is it difficult to merge this pull request?

**Comment by pioneerskies** [comment]
Aheeemmm.... @mapyo you're catching me not prepared.

Actually this cannot be merged at stands. We should go for another one, testing with newer ruby version, fixing the CI and so on.

Unfortunately I neither known this one was here waiting for Godot and I really sorry about that.

**Comment by Korkey128k** [comment]
@pioneerskies I updated the dependencies/version and tests passed. Can't modify the CI config though. I'd love to get this merged, let me know if I can do anything else to help. 😃

**Comment by pioneerskies** [comment]
@Korkey128k @mapyo I'm going to close this PR in favour of #23 .

I've almost copied the updates from this one, but I opened a bit the scope of my PR updating ruby too, moving the CI to GH Actions, (re)introduced rubocop and (re)added it to CI. That was too much to ask for iteration inside this PR and unfortunately I'll have no more time this month to be able to follow/review iterations.

Kudos to @Korkey128k for the updates you've done.

I hope you'll be able to test out the new release and eventually come back with issues in the tracker :)

Thank you so much 🙇

**Comment by pioneerskies** [comment]
https://github.com/welaika/photocopier/releases/tag/v1.4.0

**Comment by pioneerskies** [comment]
Wordmove was updated in order to include the latest Photocpier release: https://github.com/welaika/wordmove/releases/tag/v5.2.1 cheers

**Pull request closed without merging**
